/* =====================================================================
   05 - VALIDAÇÕES E EVIDÊNCIAS  (conectado ao BDIBPBMSA_DEV)
   ---------------------------------------------------------------------
   1. Estrutura: recaptura o catálogo CI da PRD e do DEV e compara objeto
      a objeto (EXCEPT nos dois sentidos). Zero diferença = idênticos.
   2. Registros: contagem e soma de verificação (CHECKSUM_AGG de
      BINARY_CHECKSUM das colunas gravadas) por tabela, calculadas DENTRO
      de cada banco.
   3. Identity e sequences: o próximo valor igual ao da PRD.
   4. Integridade referencial: DBCC CHECKCONSTRAINTS WITH ALL_CONSTRAINTS
      em todas as tabelas CI do DEV, e confiabilidade (is_not_trusted)
      das FKs/CHECKs igual à da PRD.
   5. Veredito por critério de aceite.

   Só lê (exceto as tabelas MIG). A PRD está em uso: linha gravada lá
   depois do 03 aparece como divergência de contagem — rode em janela de
   baixa atividade ou repita o 03/05 para as tabelas apontadas.
   ===================================================================== */

SET NOCOUNT ON;

DECLARE @ini INT = ISNULL((SELECT MAX(ID) FROM MIG.EVIDENCIA), 0);
DECLARE @sql NVARCHAR(MAX), @tab SYSNAME, @cols NVARCHAR(MAX), @n INT, @m INT, @d NVARCHAR(MAX);

EXEC MIG.SP_SNAPSHOT 'PRD';
EXEC MIG.SP_SNAPSHOT 'DEV';

/* ── 1. Estrutura ──────────────────────────────────────────────────── */
DELETE MIG.DIFERENCA;
DECLARE @ent TABLE (ENTIDADE VARCHAR(20), TABELA_CAT SYSNAME, COLUNAS NVARCHAR(MAX), CHAVE NVARCHAR(400));
INSERT @ent VALUES
 ('TABELA',    'CAT_TABELA',    N'TABELA, NAO_SUPORTADO, ESCALONAMENTO, COMPRESSAO_HEAP', N'TABELA'),
 ('COLUNA',    'CAT_COLUNA',    N'TABELA, ORDEM, COLUNA, TIPO, COLLATION_, NULO, IDENTIDADE, SEMENTE, INCREMENTO, IDENT_NFR, CALCULADA, DEF_CALCULADA, PERSISTIDA, NM_DEFAULT, DEF_DEFAULT, ROWGUIDCOL_, ESPARSA, MASCARA, ROWVERSION_', N'TABELA + N''.'' + COLUNA'),
 ('PK/UNIQUE', 'CAT_CHAVE',     N'TABELA, NOME, TIPO, AGRUPAMENTO, COLUNAS, OPCOES', N'TABELA + N''.'' + NOME'),
 ('INDICE',    'CAT_INDICE',    N'OBJETO, OBJETO_TIPO, NOME, TIPO, UNICO, COLUNAS, INCLUIDAS, FILTRO, OPCOES, DESABILITADO', N'OBJETO + N''.'' + NOME'),
 ('CHECK',     'CAT_CHECK',     N'TABELA, NOME, DEFINICAO, DESABILITADA, NAO_CONFIAVEL, NAO_REPLICACAO', N'TABELA + N''.'' + NOME'),
 ('FK',        'CAT_FK',        N'TABELA, NOME, COLUNAS, REF_ESQUEMA, REF_TABELA, REF_COLUNAS, ACAO_DELETE, ACAO_UPDATE, DESABILITADA, NAO_CONFIAVEL, NAO_REPLICACAO', N'TABELA + N''.'' + NOME'),
 ('MODULO',    'CAT_MODULO',    N'NOME, TIPO, TABELA_PAI, DEFINICAO, ANSI_NULLS_, QUOTED_ID, SCHEMABINDING_, DESABILITADO, INSTEAD_OF, ORDEM_TRIGGER', N'NOME'),
 ('SEQUENCE',  'CAT_SEQUENCIA', N'NOME, TIPO, INICIO, INCREMENTO, MINIMO, MAXIMO, CICLO, CACHE_, PROXIMO', N'NOME'),
 ('SINONIMO',  'CAT_SINONIMO',  N'NOME, BASE', N'NOME'),
 ('EXTPROP',   'CAT_EXTPROP',   N'OBJETO, OBJETO_TIPO, PAI, NIVEL2_TIPO, NIVEL2, NOME, VALOR', N'OBJETO + ISNULL(N''.'' + NIVEL2, N'''') + N'' ['' + NOME + N'']''');

DECLARE @e VARCHAR(20), @tc SYSNAME, @ch NVARCHAR(400);
DECLARE ce CURSOR LOCAL FAST_FORWARD FOR SELECT ENTIDADE, TABELA_CAT, COLUNAS, CHAVE FROM @ent;
OPEN ce;
FETCH NEXT FROM ce INTO @e, @tc, @cols, @ch;
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @sql = N'INSERT MIG.DIFERENCA (ENTIDADE, LADO, CHAVE, DETALHE)
        SELECT @e, N''SO_PRD'', ' + @ch + N', (SELECT x.* FOR JSON PATH, WITHOUT_ARRAY_WRAPPER)
        FROM (SELECT ' + @cols + N' FROM MIG.' + @tc + N' WHERE ORIGEM = ''PRD''
              EXCEPT SELECT ' + @cols + N' FROM MIG.' + @tc + N' WHERE ORIGEM = ''DEV'') x;
        INSERT MIG.DIFERENCA (ENTIDADE, LADO, CHAVE, DETALHE)
        SELECT @e, N''SO_DEV'', ' + @ch + N', (SELECT x.* FOR JSON PATH, WITHOUT_ARRAY_WRAPPER)
        FROM (SELECT ' + @cols + N' FROM MIG.' + @tc + N' WHERE ORIGEM = ''DEV''
              EXCEPT SELECT ' + @cols + N' FROM MIG.' + @tc + N' WHERE ORIGEM = ''PRD'') x;';
    EXEC sp_executesql @sql, N'@e VARCHAR(20)', @e = @e;

    SET @sql = N'SELECT @n = (SELECT COUNT(*) FROM MIG.' + @tc + N' WHERE ORIGEM = ''PRD''),
                        @m = (SELECT COUNT(*) FROM MIG.' + @tc + N' WHERE ORIGEM = ''DEV'');';
    EXEC sp_executesql @sql, N'@n INT OUTPUT, @m INT OUTPUT', @n = @n OUTPUT, @m = @m OUTPUT;
    SET @d = N'PRD ' + CAST(@n AS NVARCHAR(10)) + N' | DEV ' + CAST(@m AS NVARCHAR(10)) + N' | diferenças '
           + CAST((SELECT COUNT(*) FROM MIG.DIFERENCA WHERE ENTIDADE = @e) AS NVARCHAR(10));
    INSERT MIG.EVIDENCIA (ETAPA, ITEM, RESULTADO, DETALHE)
    VALUES ('05', N'Estrutura — ' + @e, CASE WHEN EXISTS (SELECT 1 FROM MIG.DIFERENCA WHERE ENTIDADE = @e) THEN 'FALHA' ELSE 'OK' END, @d);
    FETCH NEXT FROM ce INTO @e, @tc, @cols, @ch;
END
CLOSE ce; DEALLOCATE ce;

/* ── 2. Contagem e soma de verificação ─────────────────────────────── */
DELETE MIG.CONTAGEM;
DECLARE ct CURSOR LOCAL FAST_FORWARD FOR SELECT TABELA FROM MIG.CAT_TABELA WHERE ORIGEM = 'PRD' ORDER BY TABELA;
OPEN ct;
FETCH NEXT FROM ct INTO @tab;
WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @cols = STRING_AGG(CONVERT(NVARCHAR(MAX), QUOTENAME(COLUNA)), N', ') WITHIN GROUP (ORDER BY ORDEM)
    FROM MIG.CAT_COLUNA WHERE ORIGEM = 'PRD' AND TABELA = @tab AND CALCULADA = 0 AND ROWVERSION_ = 0;
    SET @sql = N'SELECT TABELA = CAST(N''' + REPLACE(@tab, N'''', N'''''') + N''' AS NVARCHAR(128)), QTD = COUNT_BIG(*),
                        SOMA = CHECKSUM_AGG(BINARY_CHECKSUM(' + @cols + N')) FROM CI.' + QUOTENAME(@tab);
    BEGIN TRY
        INSERT MIG.CONTAGEM (TABELA, QTD, SOMA_VERIFICACAO, SHARD) EXEC MIG.SP_EXEC_ORIGEM @sql;
        UPDATE MIG.CONTAGEM SET ORIGEM = 'PRD' WHERE ORIGEM IS NULL;
        INSERT MIG.CONTAGEM (TABELA, QTD, SOMA_VERIFICACAO, SHARD) EXEC MIG.SP_EXEC_DESTINO @sql;
        UPDATE MIG.CONTAGEM SET ORIGEM = 'DEV' WHERE ORIGEM IS NULL;
    END TRY
    BEGIN CATCH
        SET @d = N'CI.' + @tab + N': ' + ERROR_MESSAGE();
        EXEC MIG.SP_EVIDENCIA '05', N'Contagem não executada', 'FALHA', @d;
    END CATCH
    FETCH NEXT FROM ct INTO @tab;
END
CLOSE ct; DEALLOCATE ct;

INSERT MIG.EVIDENCIA (ETAPA, ITEM, RESULTADO, DETALHE)
SELECT '05', N'Registros — CI.' + p.TABELA,
       CASE WHEN d.QTD = p.QTD AND ISNULL(d.SOMA_VERIFICACAO, 0) = ISNULL(p.SOMA_VERIFICACAO, 0) THEN 'OK' ELSE 'FALHA' END,
       N'PRD ' + CAST(p.QTD AS NVARCHAR(20)) + N' | DEV ' + ISNULL(CAST(d.QTD AS NVARCHAR(20)), N'-')
       + N' | soma de verificação ' + CASE WHEN ISNULL(d.SOMA_VERIFICACAO, 0) = ISNULL(p.SOMA_VERIFICACAO, 0) THEN N'igual' ELSE N'DIFERENTE' END
FROM MIG.CONTAGEM p LEFT JOIN MIG.CONTAGEM d ON d.ORIGEM = 'DEV' AND d.TABELA = p.TABELA
WHERE p.ORIGEM = 'PRD';

/* ── 3. Identity e sequences: próximo valor ───────────────────────── */
INSERT MIG.EVIDENCIA (ETAPA, ITEM, RESULTADO, DETALHE)
SELECT '05', N'Identity — CI.' + p.TABELA + N'.' + p.COLUNA,
       CASE WHEN x.PROX_PRD = x.PROX_DEV OR (p.ULTIMO_IDENTITY IS NULL AND d.ULTIMO_IDENTITY IS NULL) THEN 'OK' ELSE 'FALHA' END,
       N'próximo valor PRD ' + ISNULL(CAST(x.PROX_PRD AS NVARCHAR(40)), N'(semente)') + N' | DEV ' + ISNULL(CAST(x.PROX_DEV AS NVARCHAR(40)), N'(semente)')
FROM MIG.CAT_COLUNA p
JOIN MIG.CAT_COLUNA d ON d.ORIGEM = 'DEV' AND d.TABELA = p.TABELA AND d.COLUNA = p.COLUNA
CROSS APPLY (SELECT
    PROX_PRD = CAST(p.ULTIMO_IDENTITY AS DECIMAL(38,0)) + CAST(p.INCREMENTO AS DECIMAL(38,0)),
    /* DEV: tabela vazia recebeu RESEED no próprio próximo valor (04). */
    PROX_DEV = CAST(d.ULTIMO_IDENTITY AS DECIMAL(38,0))
             + CASE WHEN ISNULL((SELECT QTD FROM MIG.CONTAGEM c WHERE c.ORIGEM = 'DEV' AND c.TABELA = d.TABELA), 0) > 0
                    THEN CAST(d.INCREMENTO AS DECIMAL(38,0)) ELSE 0 END) x
WHERE p.ORIGEM = 'PRD' AND p.IDENTIDADE = 1;
-- sequences: o PROXIMO já entra na comparação estrutural (entidade SEQUENCE).

/* ── 4. Integridade referencial ───────────────────────────────────── */
DELETE MIG.VIOLACAO;
DECLARE cv CURSOR LOCAL FAST_FORWARD FOR SELECT name FROM sys.tables WHERE schema_id = SCHEMA_ID('CI') ORDER BY name;
OPEN cv;
FETCH NEXT FROM cv INTO @tab;
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @sql = N'DBCC CHECKCONSTRAINTS (N''CI.' + REPLACE(QUOTENAME(@tab), N'''', N'''''') + N''') WITH ALL_CONSTRAINTS, NO_INFOMSGS;';
    INSERT MIG.VIOLACAO (TABELA, [CONSTRAINT], ONDE) EXEC (@sql);
    FETCH NEXT FROM cv INTO @tab;
END
CLOSE cv; DEALLOCATE cv;

/* Violação em constraint que já não era confiável/ativa na PRD vem da
   origem (o dado já estava assim lá) — AVISO. Em constraint confiável é
   perda de integridade — FALHA. */
INSERT MIG.EVIDENCIA (ETAPA, ITEM, RESULTADO, DETALHE)
SELECT '05', N'Integridade — ' + v.[CONSTRAINT],
       CASE WHEN k.NAO_CONFIAVEL = 1 OR k.DESABILITADA = 1 THEN 'AVISO' ELSE 'FALHA' END,
       CAST(COUNT(*) AS NVARCHAR(10)) + N' linha(s) em ' + MIN(v.TABELA)
       + CASE WHEN k.NAO_CONFIAVEL = 1 OR k.DESABILITADA = 1
              THEN N' — pré-existente: a constraint é não confiável/desabilitada também na PRD.' ELSE N'' END
FROM MIG.VIOLACAO v
OUTER APPLY (SELECT TOP (1) NAO_CONFIAVEL, DESABILITADA FROM (
                 SELECT NOME, NAO_CONFIAVEL, DESABILITADA FROM MIG.CAT_FK WHERE ORIGEM = 'PRD'
                 UNION ALL SELECT NOME, NAO_CONFIAVEL, DESABILITADA FROM MIG.CAT_CHECK WHERE ORIGEM = 'PRD') q
             WHERE QUOTENAME(q.NOME) = v.[CONSTRAINT] OR q.NOME = v.[CONSTRAINT]) k
GROUP BY v.[CONSTRAINT], k.NAO_CONFIAVEL, k.DESABILITADA;

SELECT @n = COUNT(*), @m = SUM(CASE WHEN NAO_CONFIAVEL = 0 THEN 1 ELSE 0 END) FROM MIG.CAT_FK WHERE ORIGEM = 'DEV';
SET @d = CAST(@n AS NVARCHAR(10)) + N' FK(s) no DEV, ' + CAST(ISNULL(@m, 0) AS NVARCHAR(10)) + N' confiável(is) (validadas sobre os dados); PRD: '
       + CAST((SELECT COUNT(*) FROM MIG.CAT_FK WHERE ORIGEM = 'PRD') AS NVARCHAR(10)) + N' FK(s), '
       + CAST((SELECT COUNT(*) FROM MIG.CAT_FK WHERE ORIGEM = 'PRD' AND NAO_CONFIAVEL = 0) AS NVARCHAR(10)) + N' confiável(is).';
INSERT MIG.EVIDENCIA (ETAPA, ITEM, RESULTADO, DETALHE)
VALUES ('05', N'Integridade — FKs confiáveis',
        CASE WHEN @m = (SELECT COUNT(*) FROM MIG.CAT_FK WHERE ORIGEM = 'PRD' AND NAO_CONFIAVEL = 0)
              AND @n = (SELECT COUNT(*) FROM MIG.CAT_FK WHERE ORIGEM = 'PRD') THEN 'OK' ELSE 'FALHA' END, @d);
IF NOT EXISTS (SELECT 1 FROM MIG.VIOLACAO)
    EXEC MIG.SP_EVIDENCIA '05', N'Integridade — DBCC CHECKCONSTRAINTS', 'OK', N'Nenhuma linha viola FK ou CHECK no schema CI do DEV.';

/* ── 5. Veredito por critério de aceite ───────────────────────────── */
DECLARE @crit TABLE (ORDEM INT, CRITERIO NVARCHAR(200), RESULTADO VARCHAR(10), DETALHE NVARCHAR(MAX));
INSERT @crit
SELECT 1, N'Todas as tabelas CI da PRD existem no DEV',
       CASE WHEN EXISTS (SELECT 1 FROM MIG.DIFERENCA WHERE ENTIDADE = 'TABELA') THEN 'FALHA' ELSE 'OK' END,
       CAST((SELECT COUNT(*) FROM MIG.CAT_TABELA WHERE ORIGEM = 'DEV') AS NVARCHAR(10)) + N' de '
       + CAST((SELECT COUNT(*) FROM MIG.CAT_TABELA WHERE ORIGEM = 'PRD') AS NVARCHAR(10))
UNION ALL
SELECT 2, N'Estruturas idênticas (colunas, tipos, PK, FK, índices, defaults, constraints, identity, triggers, dependentes)',
       CASE WHEN EXISTS (SELECT 1 FROM MIG.DIFERENCA) THEN 'FALHA' ELSE 'OK' END,
       CAST((SELECT COUNT(*) FROM MIG.DIFERENCA) AS NVARCHAR(10)) + N' diferença(s)'
UNION ALL
SELECT 3, N'Quantidade de registros conciliada',
       CASE WHEN EXISTS (SELECT 1 FROM MIG.EVIDENCIA WHERE ID > @ini AND ITEM LIKE N'Registros — %' AND RESULTADO <> 'OK')
              OR EXISTS (SELECT 1 FROM MIG.EVIDENCIA WHERE ID > @ini AND ITEM = N'Contagem não executada') THEN 'FALHA' ELSE 'OK' END,
       N'PRD ' + CAST((SELECT SUM(QTD) FROM MIG.CONTAGEM WHERE ORIGEM = 'PRD') AS NVARCHAR(20)) + N' | DEV '
       + CAST((SELECT SUM(QTD) FROM MIG.CONTAGEM WHERE ORIGEM = 'DEV') AS NVARCHAR(20)) + N' linha(s); soma de verificação por tabela'
UNION ALL
SELECT 4, N'Nenhuma constraint ou relacionamento perdido',
       CASE WHEN EXISTS (SELECT 1 FROM MIG.DIFERENCA WHERE ENTIDADE IN ('PK/UNIQUE','FK','CHECK','INDICE','COLUNA')) THEN 'FALHA' ELSE 'OK' END,
       CAST((SELECT COUNT(*) FROM MIG.CAT_CHAVE WHERE ORIGEM = 'DEV') AS NVARCHAR(10)) + N' PK/UNIQUE, '
       + CAST((SELECT COUNT(*) FROM MIG.CAT_FK WHERE ORIGEM = 'DEV') AS NVARCHAR(10)) + N' FK, '
       + CAST((SELECT COUNT(*) FROM MIG.CAT_CHECK WHERE ORIGEM = 'DEV') AS NVARCHAR(10)) + N' CHECK, '
       + CAST((SELECT COUNT(*) FROM MIG.CAT_COLUNA WHERE ORIGEM = 'DEV' AND NM_DEFAULT IS NOT NULL) AS NVARCHAR(10)) + N' DEFAULT'
UNION ALL
SELECT 5, N'Integridade referencial válida',
       CASE WHEN EXISTS (SELECT 1 FROM MIG.EVIDENCIA WHERE ID > @ini AND ITEM LIKE N'Integridade — %' AND RESULTADO = 'FALHA') THEN 'FALHA'
            WHEN EXISTS (SELECT 1 FROM MIG.EVIDENCIA WHERE ID > @ini AND ITEM LIKE N'Integridade — %' AND RESULTADO = 'AVISO') THEN 'AVISO'
            ELSE 'OK' END,
       CAST((SELECT COUNT(*) FROM MIG.VIOLACAO) AS NVARCHAR(10)) + N' linha(s) violando constraint'
UNION ALL
SELECT 6, N'Identity e sequences com o mesmo próximo valor',
       CASE WHEN EXISTS (SELECT 1 FROM MIG.EVIDENCIA WHERE ID > @ini AND ITEM LIKE N'Identity — %' AND RESULTADO <> 'OK')
              OR EXISTS (SELECT 1 FROM MIG.DIFERENCA WHERE ENTIDADE = 'SEQUENCE') THEN 'FALHA' ELSE 'OK' END,
       CAST((SELECT COUNT(*) FROM MIG.EVIDENCIA WHERE ID > @ini AND ITEM LIKE N'Identity — %') AS NVARCHAR(10)) + N' identity, '
       + CAST((SELECT COUNT(*) FROM MIG.CAT_SEQUENCIA WHERE ORIGEM = 'DEV') AS NVARCHAR(10)) + N' sequence(s)'
UNION ALL
SELECT 7, N'Dependências fora do CI mapeadas',
       CASE WHEN EXISTS (SELECT 1 FROM MIG.CAT_DEPEXT WHERE ORIGEM = 'PRD') THEN 'AVISO' ELSE 'OK' END,
       ISNULL((SELECT STRING_AGG(TIPO + N': ' + OBJETO_FORA + N' / CI.' + OBJETO_CI, N'; ') FROM MIG.CAT_DEPEXT WHERE ORIGEM = 'PRD'),
              N'Nenhuma');

INSERT MIG.EVIDENCIA (ETAPA, ITEM, RESULTADO, DETALHE)
SELECT '05', N'Critério ' + CAST(ORDEM AS NVARCHAR(2)) + N': ' + CRITERIO, RESULTADO, DETALHE FROM @crit;

/* ── Evidências ────────────────────────────────────────────────────── */
SELECT VEREDITO = CASE WHEN EXISTS (SELECT 1 FROM @crit WHERE RESULTADO = 'FALHA') THEN 'REPROVADA' ELSE 'APROVADA' END,
       EXECUTADO_EM = SYSDATETIME(), ORIGEM = (SELECT BANCO_ORIGEM FROM MIG.PARAMETRO), DESTINO = DB_NAME();

SELECT ORDEM, CRITERIO, RESULTADO, DETALHE FROM @crit ORDER BY ORDEM;

SELECT TABELA = p.TABELA, LINHAS_PRD = p.QTD, LINHAS_DEV = d.QTD,
       SOMA_PRD = p.SOMA_VERIFICACAO, SOMA_DEV = d.SOMA_VERIFICACAO,
       RESULTADO = CASE WHEN d.QTD = p.QTD AND ISNULL(d.SOMA_VERIFICACAO, 0) = ISNULL(p.SOMA_VERIFICACAO, 0) THEN 'OK' ELSE 'FALHA' END
FROM MIG.CONTAGEM p LEFT JOIN MIG.CONTAGEM d ON d.ORIGEM = 'DEV' AND d.TABELA = p.TABELA
WHERE p.ORIGEM = 'PRD' ORDER BY p.TABELA;

SELECT ETAPA, RESULTADO, ITEM, DETALHE FROM MIG.EVIDENCIA
WHERE ID > @ini AND ITEM NOT LIKE N'Registros — %' AND ITEM NOT LIKE N'Critério %'
ORDER BY CASE RESULTADO WHEN 'FALHA' THEN 0 WHEN 'AVISO' THEN 1 ELSE 2 END, ID;

IF EXISTS (SELECT 1 FROM MIG.DIFERENCA) SELECT ENTIDADE, LADO, CHAVE, DETALHE FROM MIG.DIFERENCA ORDER BY ENTIDADE, CHAVE, LADO;
IF EXISTS (SELECT 1 FROM MIG.VIOLACAO)  SELECT TABELA, [CONSTRAINT], ONDE FROM MIG.VIOLACAO ORDER BY TABELA;

SELECT ETAPA, CARGA_TABELA = TABELA, NIVEL, ORDEM, LINHAS, DURACAO_MS = DATEDIFF(MILLISECOND, INICIO, FIM), STATUS
FROM MIG.CARGA_LOG CROSS JOIN (SELECT ETAPA = '03') e ORDER BY ORDEM;
GO
