/* =====================================================================
   ESTRUTURA COMPLETA DO SCHEMA CI  (script único)
   ---------------------------------------------------------------------
   Cria, num banco vazio (ex.: BDIBPBMSA_DEV), as tabelas do schema CI e
   todas as ligações: sequences, colunas (tipo, collation, defaults),
   PKs, UNIQUEs, índices, CHECKs, FKs, triggers e propriedades
   estendidas. Não copia dados.

   Estrutura = BDIBPBMSA_PRD conforme o dicionário "Estrutura_Atual_do_
   banco.xlsx" (30/09/2026), já com KZN_ADMIN.CD_MATRICULA VARCHAR(30)
   (alterar_kzn_admin_cd_matricula_varchar30.sql). Colunas, PKs, FKs,
   índices e ordem das colunas iguais às da PRD.

   O dicionário não traz collation, defaults, CHECKs, triggers nem
   identity: esses vêm das definições do repositório; KZN_MDM_HIERARQUIA
   e as matrículas usam Latin1_General_CI_AS (conferido na PRD). Para
   uma cópia exata, rode migracao_ci_prd_dev/gerar_script_estrutura_ci.sql
   na PRD.
   Fora deste script: KZN_MDM_TEMP, KZN_MDM_TERCEIROS_TEMP,
   KZN_TB_NOTIFICACAO_TESTE (excluídas a pedido) e o trigger
   TR_KZN_KAIZEN_HIERARQUIA_UPD (não compila no repositório). Na PRD,
   KZN_MDM_TERCEIROS_USUARIO.ID_USUARIO é IDENTITY (semente não conhecida):
   aqui a coluna é INT simples.

   Idempotente: só cria o que ainda não existir; nunca apaga nem altera.
   Termina com a conferência esperado x criado (tudo deve sair OK).
   ===================================================================== */
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
IF DB_NAME() = N'BDIBPBMSA_PRD' BEGIN RAISERROR('Abortado: a PRD já tem esta estrutura; este script é para um banco vazio (ex.: BDIBPBMSA_DEV).', 16, 1); SET NOEXEC ON; END
GO
IF SCHEMA_ID(N'CI') IS NULL EXEC (N'CREATE SCHEMA CI AUTHORIZATION dbo;');
GO
/* ── Sequences ── */
IF OBJECT_ID(N'CI.[SEQ_KZN_LOG_PVC]', N'SO') IS NULL
    CREATE SEQUENCE CI.[SEQ_KZN_LOG_PVC] AS int START WITH 1 INCREMENT BY 1 MINVALUE -2147483648 MAXVALUE 2147483647 NO CYCLE CACHE;
GO
IF OBJECT_ID(N'CI.[SEQ_KZN_LOG_PVC_DETALHE]', N'SO') IS NULL
    CREATE SEQUENCE CI.[SEQ_KZN_LOG_PVC_DETALHE] AS int START WITH 1 INCREMENT BY 1 MINVALUE -2147483648 MAXVALUE 2147483647 NO CYCLE CACHE;
GO
/* ── Tabelas ── */
IF OBJECT_ID(N'CI.[KZN_ADMIN]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_ADMIN] (
    [ID_ADMIN] int NOT NULL,
    [CD_MATRICULA] varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_ADMIN_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NOT NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_ADMIN_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_ADMIN] PRIMARY KEY CLUSTERED ([ID_ADMIN] ASC, [CD_MATRICULA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_ANALISE_DUPLICIDADE]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_ANALISE_DUPLICIDADE] (
    [ID_KAIZEN] int NULL,
    [ID_KAIZEN_DUPLICADO] int NULL,
    [PCT_DUPLICIDADE] float(53) NULL,
    [STATUS_ANALISE] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_ANALISE_DUP_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL
);
END
GO
IF OBJECT_ID(N'CI.[KZN_APROVADOR]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_APROVADOR] (
    [ID_APROVADOR] int NOT NULL,
    [CD_MATRICULA] varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_APROVADOR_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NOT NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_APROVADOR_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_APROVADOR] PRIMARY KEY CLUSTERED ([ID_APROVADOR] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_APROVADOR_ID] UNIQUE NONCLUSTERED ([ID_APROVADOR] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_CATEGORIA]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_CATEGORIA] (
    [ID_CATEGORIA] int NOT NULL,
    [ID_IDIOMA] int NOT NULL,
    [URL_ICONE] varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_CATEGORIA] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DS_CATEGORIA] varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_CATEGORIA_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_CATEGORIA_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_CATEGORIA] PRIMARY KEY CLUSTERED ([ID_CATEGORIA] ASC, [ID_IDIOMA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_CATEGORIA_NM] UNIQUE NONCLUSTERED ([ID_IDIOMA] ASC, [NM_CATEGORIA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_DESPERDICIO]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_DESPERDICIO] (
    [ID_DESPERDICIO] int NOT NULL,
    [ID_IDIOMA] int NOT NULL,
    [URL_ICONE] varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_DESPERDICIO] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DS_DESPERDICIO] varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_DESPERDICIO_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_DESPERDICIO_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_DESPERDICIO] PRIMARY KEY CLUSTERED ([ID_DESPERDICIO] ASC, [ID_IDIOMA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_DESPERDICIO_NM] UNIQUE NONCLUSTERED ([ID_IDIOMA] ASC, [NM_DESPERDICIO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_HIST_APROVADOR]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_HIST_APROVADOR] (
    [ID_APROVADOR] int NOT NULL,
    [CD_MATRICULA] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_HIST_APROVADOR_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_HIST_APROVADOR_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_HIST_APROVADOR] PRIMARY KEY CLUSTERED ([ID_APROVADOR] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_HIST_KAIZEN_DESPERDICIO]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_HIST_KAIZEN_DESPERDICIO] (
    [ID_KAIZEN] int NOT NULL,
    [ID_DESPERDICIO] int NULL,
    [DT_ATUALIZACAO] datetime2(7) NOT NULL
);
END
GO
IF OBJECT_ID(N'CI.[KZN_HIST_KAIZEN_HIERARQUIA]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_HIST_KAIZEN_HIERARQUIA] (
    [ID_KAIZEN] int NOT NULL,
    [ID_USUARIO_LIDER] int NOT NULL,
    [NM_HIERARQUIA_N1] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N2] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N3] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N4] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N5] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N6] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N7] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N8] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DT_ATUALIZACAO] datetime2(3) NOT NULL
);
END
GO
IF OBJECT_ID(N'CI.[KZN_HIST_MDM_VBM_TERC]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_HIST_MDM_VBM_TERC] (
    [ID_USUARIO] int NOT NULL,
    [CD_MATRICULA] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ID_TIPO_USUARIO] int NULL,
    [NM_USUARIO] varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CD_EMAIL] varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_SITUACAO] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_POSICAO] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_EMPRESA] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_PAIS] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_ESTADO] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_CIDADE] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_SITE] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N1] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N2] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N3] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N4] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N5] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N6] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N7] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N8] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DT_ATUALIZACAO] datetime2(3) NULL,
    CONSTRAINT [PK_KZN_HIST_MDM_VBM_TERC] PRIMARY KEY CLUSTERED ([ID_USUARIO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_HIST_MEMBROS_EQUIPE]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_HIST_MEMBROS_EQUIPE] (
    [ID_KAIZEN] int NOT NULL,
    [ID_USUARIO] int NOT NULL,
    [DT_ATUALIZACAO] datetime2(7) NULL
);
END
GO
IF OBJECT_ID(N'CI.[KZN_HIST_PEDRAVISAOCONSOLIDADA]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_HIST_PEDRAVISAOCONSOLIDADA] (
    [ID_KAIZEN] int NOT NULL,
    [ID_USUARIO_CADASTRO] int NOT NULL,
    [ID_USUARIO_LIDER] int NOT NULL,
    [NM_KAIZEN] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ID_CATEGORIA] int NULL,
    [ID_REPLICACAO] int NULL,
    [DS_PROBLEMA] varchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DS_OBJETIVO] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ID_APROVADOR] int NULL,
    [URL_IMG_ANTES] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DS_ESTADO_ANTES] varchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [URL_IMG_DEPOIS] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DS_ESTADO_DEPOIS] varchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [URL_REFERENCIA] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DS_COMPARA_META] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DS_LICOES_APRENDIDAS] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [VL_RESULTADO_FINANCEIRO] decimal(18,2) NULL,
    [ID_MOEDA] int NULL,
    [DS_RESULTADO_ALCANCADO] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DT_CONCLUSAO] date NULL,
    [DT_CRIACAO] datetime2(3) NOT NULL,
    [ID_USUARIO_ATUALIZACAO] int NOT NULL,
    [DS_MOTIVO] varchar(1200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ID_STATUS] int NULL
);
END
GO
IF OBJECT_ID(N'CI.[KZN_HIST_RESULTADO_KAIZEN]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_HIST_RESULTADO_KAIZEN] (
    [ID_KAIZEN] int NOT NULL,
    [ID_RESULTADO] int NOT NULL,
    [DT_ATUALIZACAO] datetime2(3) NOT NULL
);
END
GO
IF OBJECT_ID(N'CI.[KZN_IDIOMA]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_IDIOMA] (
    [ID_IDIOMA] int NOT NULL,
    [URL_ICONE] varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_IDIOMA] varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [NM_IDIOMA] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [NM_PAIS] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_IDIOMA_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_IDIOMA_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_IDIOMA] PRIMARY KEY CLUSTERED ([ID_IDIOMA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_IDIOMA_SG] UNIQUE NONCLUSTERED ([SG_IDIOMA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_KAIZEN_DESPERDICIO]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_KAIZEN_DESPERDICIO] (
    [ID_KAIZEN] int NOT NULL,
    [ID_DESPERDICIO] int NOT NULL,
    [DT_ATUALIZACAO] datetime2(7) CONSTRAINT [DF_KZN_KZDESP_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_KZDESP] PRIMARY KEY CLUSTERED ([ID_KAIZEN] ASC, [ID_DESPERDICIO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_KAIZEN_HIERARQUIA]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_KAIZEN_HIERARQUIA] (
    [ID_KAIZEN] int NOT NULL,
    [ID_USUARIO_LIDER] int NOT NULL,
    [NM_HIERARQUIA_N1] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N2] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N3] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N4] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N5] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N6] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N7] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_HIERARQUIA_N8] varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_KAIZEN_HIERARQUIA_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_KAIZEN_HIERARQUIA] PRIMARY KEY CLUSTERED ([ID_KAIZEN] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA] (
    [ID_LOG] int NOT NULL,
    [ID_KAIZEN] int NOT NULL,
    [TP_OPERACAO] char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DT_OPERACAO] datetime2(3) CONSTRAINT [DF_KZN_LOG_PVC_DT_OPERACAO] DEFAULT (sysdatetime()) NOT NULL,
    [ID_USUARIO_OPERACAO] int NOT NULL,
    CONSTRAINT [PK_KZN_LOG_PVC] PRIMARY KEY CLUSTERED ([ID_LOG] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA_DETALHE]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA_DETALHE] (
    [ID_LOG_DETALHE] int NOT NULL,
    [ID_LOG] int NOT NULL,
    [NM_CAMPO] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [VL_ANTERIOR] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [VL_NOVO] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT [PK_KZN_LOG_PVC_DETALHE] PRIMARY KEY CLUSTERED ([ID_LOG_DETALHE] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_MDM_HIERARQUIA]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_MDM_HIERARQUIA] (
    [ID_USUARIO] int NOT NULL,
    [CD_MATRICULA] varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
    [ID_TIPO_USUARIO] int NOT NULL,
    [NM_USUARIO] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [CD_EMAIL] varchar(100) COLLATE Latin1_General_CI_AS NULL,
    [NM_SITUACAO] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [SG_ATIVO] varchar(1) COLLATE Latin1_General_CI_AS CONSTRAINT [DF_KZN_MDM_HIERARQUIA_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [NM_POSICAO] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [NM_EMPRESA] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [NM_PAIS] varchar(30) COLLATE Latin1_General_CI_AS NULL,
    [NM_ESTADO] varchar(30) COLLATE Latin1_General_CI_AS NULL,
    [NM_CIDADE] varchar(30) COLLATE Latin1_General_CI_AS NULL,
    [NM_SITE] varchar(30) COLLATE Latin1_General_CI_AS NULL,
    [NM_HIERARQUIA_N1] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [NM_HIERARQUIA_N2] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [NM_HIERARQUIA_N3] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [NM_HIERARQUIA_N4] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [NM_HIERARQUIA_N5] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [NM_HIERARQUIA_N6] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [NM_HIERARQUIA_N7] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [NM_HIERARQUIA_N8] varchar(80) COLLATE Latin1_General_CI_AS NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_MDM_HIERARQUIA_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_MDM_HIERARQUIA] PRIMARY KEY CLUSTERED ([ID_USUARIO] ASC, [CD_MATRICULA] ASC, [ID_TIPO_USUARIO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_MDM_HIERARQUIA_MATR] UNIQUE NONCLUSTERED ([CD_MATRICULA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_MDM_HIERARQUIA_USUARIO] UNIQUE NONCLUSTERED ([ID_USUARIO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_MDM_TERCEIROS_USUARIO]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_MDM_TERCEIROS_USUARIO] (
    [ID_USUARIO] int NOT NULL,
    [CD_MATRICULA] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DT_CRIACAO] datetime2(3) NOT NULL,
    [DT_ATUALIZACAO] datetime2(3) NOT NULL,
    CONSTRAINT [PK_KZN_MDM_TERCEIROS_USUARIO] PRIMARY KEY CLUSTERED ([ID_USUARIO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_MDM_TERCEIROS_USUARIO_CD_MATRICULA] UNIQUE NONCLUSTERED ([CD_MATRICULA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_MEMBROS_EQUIPE]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_MEMBROS_EQUIPE] (
    [ID_KAIZEN] int NOT NULL,
    [ID_USUARIO] int NOT NULL,
    [DT_ATUALIZACAO] datetime2(7) NULL,
    CONSTRAINT [PK_kzn_membros_equipe] PRIMARY KEY CLUSTERED ([ID_KAIZEN] ASC, [ID_USUARIO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_MOEDA]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_MOEDA] (
    [ID_MOEDA] int NOT NULL,
    [NM_MOEDA] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [SG_MOEDA] char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [NM_PAIS] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_MOEDA_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_MOEDA_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_MOEDA] PRIMARY KEY CLUSTERED ([ID_MOEDA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_MOEDA_SG] UNIQUE NONCLUSTERED ([SG_MOEDA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_PEDRAVISAOCONSOLIDADA]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_PEDRAVISAOCONSOLIDADA] (
    [ID_KAIZEN] int NOT NULL,
    [ID_USUARIO_CADASTRO] int NOT NULL,
    [ID_USUARIO_LIDER] int NOT NULL,
    [NM_KAIZEN] varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ID_CATEGORIA] int NOT NULL,
    [ID_REPLICACAO] int NULL,
    [DS_PROBLEMA] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DS_OBJETIVO] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ID_APROVADOR] int NULL,
    [URL_IMG_ANTES] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DS_ESTADO_ANTES] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [URL_IMG_DEPOIS] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DS_ESTADO_DEPOIS] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [URL_REFERENCIA] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DS_COMPARA_META] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DS_LICOES_APRENDIDAS] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [VL_RESULTADO_FINANCEIRO] decimal(18,2) NULL,
    [ID_MOEDA] int NULL,
    [DS_RESULTADO_ALCANCADO] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DT_CONCLUSAO] date NULL,
    [DT_CRIACAO] datetime2(3) CONSTRAINT [DF_KZN_PVC_DT_CRIACAO] DEFAULT (sysdatetime()) NOT NULL,
    [ID_USUARIO_ATUALIZACAO] int NOT NULL,
    [DS_MOTIVO] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ID_STATUS] int NULL,
    [SG_GM] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_PVC_SG_GM] DEFAULT ('N') NOT NULL,
    [URL_GM] varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ID_TIPO_KAIZEN] int CONSTRAINT [DF_KZN_PVC_ID_TIPO_KAIZEN] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_KZN_PVC] PRIMARY KEY CLUSTERED ([ID_KAIZEN] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_PVC_KAIZEN_LIDER] UNIQUE NONCLUSTERED ([ID_KAIZEN] ASC, [ID_USUARIO_LIDER] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_REPLICACAO]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_REPLICACAO] (
    [ID_REPLICACAO] int NOT NULL,
    [ID_IDIOMA] int NOT NULL,
    [URL_ICONE] varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_REPLICACAO] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DS_REPLICACAO] varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_REPLICACAO_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_REPLICACAO_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_REPLICACAO] PRIMARY KEY CLUSTERED ([ID_REPLICACAO] ASC, [ID_IDIOMA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_REPLICACAO_NM] UNIQUE NONCLUSTERED ([ID_IDIOMA] ASC, [NM_REPLICACAO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_RESULTADO_KAIZEN]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_RESULTADO_KAIZEN] (
    [ID_KAIZEN] int NOT NULL,
    [ID_RESULTADO] int NOT NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_RESULTADO_KAIZEN_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_RESULTADO_KAIZEN] PRIMARY KEY CLUSTERED ([ID_KAIZEN] ASC, [ID_RESULTADO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_RESULTADOS]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_RESULTADOS] (
    [ID_RESULTADO] int NOT NULL,
    [ID_IDIOMA] int NOT NULL,
    [URL_ICONE] varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ID_TIPO_RESULTADO] int NOT NULL,
    [NM_RESULTADO] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DS_RESULTADO] varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_RESULTADOS_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_RESULTADOS_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_RESULTADOS] PRIMARY KEY CLUSTERED ([ID_RESULTADO] ASC, [ID_IDIOMA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_RESULTADOS_NM] UNIQUE NONCLUSTERED ([ID_IDIOMA] ASC, [NM_RESULTADO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_STATUS]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_STATUS] (
    [ID_STATUS] int NOT NULL,
    [ID_IDIOMA] int NOT NULL,
    [URL_ICONE] varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NM_STATUS] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DS_STATUS] varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_STATUS_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_STATUS_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_STATUS] PRIMARY KEY CLUSTERED ([ID_STATUS] ASC, [ID_IDIOMA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_STATUS_NM] UNIQUE NONCLUSTERED ([ID_IDIOMA] ASC, [NM_STATUS] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_TIPO_KAIZEN]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_TIPO_KAIZEN] (
    [ID_TIPO_KAIZEN] int NOT NULL,
    [ID_IDIOMA] int NOT NULL,
    [NM_TIPO_KAIZEN] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DS_TIPO_KAIZEN] varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_TIPO_KAIZEN_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_TIPO_KAIZEN_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_TIPO_KAIZEN] PRIMARY KEY CLUSTERED ([ID_TIPO_KAIZEN] ASC, [ID_IDIOMA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_TIPO_KAIZEN_NM] UNIQUE NONCLUSTERED ([ID_IDIOMA] ASC, [NM_TIPO_KAIZEN] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_TIPO_RESULTADO]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_TIPO_RESULTADO] (
    [ID_TIPO_RESULTADO] int NOT NULL,
    [ID_IDIOMA] int NOT NULL,
    [NM_TIPO_RESULTADO] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [SG_ATIVO] varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_KZN_TIPO_RESULTADO_SG_ATIVO] DEFAULT ('S') NOT NULL,
    [ID_USUARIO] int NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_TIPO_RESULTADO_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_TIPO_RESULTADO] PRIMARY KEY CLUSTERED ([ID_TIPO_RESULTADO] ASC, [ID_IDIOMA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_TIPO_RESULTADO_NM] UNIQUE NONCLUSTERED ([ID_IDIOMA] ASC, [NM_TIPO_RESULTADO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
IF OBJECT_ID(N'CI.[KZN_TIPO_USUARIO]', N'U') IS NULL
BEGIN
CREATE TABLE CI.[KZN_TIPO_USUARIO] (
    [ID_TIPO_USUARIO] int NOT NULL,
    [NM_USUARIO] varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ID_USUARIO] int NULL,
    [DT_ATUALIZACAO] datetime2(3) CONSTRAINT [DF_KZN_TIPO_USUARIO_DT_ATUALIZACAO] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_KZN_TIPO_USUARIO] PRIMARY KEY CLUSTERED ([ID_TIPO_USUARIO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE),
    CONSTRAINT [UQ_KZN_TIPO_USUARIO_NM] UNIQUE NONCLUSTERED ([NM_USUARIO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE)
);
END
GO
/* ── Índices ── */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_ANALISE_DUPLICIDADE]') AND name = N'IX_KZN_ANALISE_DUP_KAIZEN')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_ANALISE_DUP_KAIZEN] ON CI.[KZN_ANALISE_DUPLICIDADE] ([ID_KAIZEN] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_CATEGORIA]') AND name = N'IX_KZN_CATEGORIA_ID_IDIOMA')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_CATEGORIA_ID_IDIOMA] ON CI.[KZN_CATEGORIA] ([ID_IDIOMA] ASC) INCLUDE ([NM_CATEGORIA]) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_DESPERDICIO]') AND name = N'IX_KZN_DESPERDICIO_ID_IDIOMA')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_DESPERDICIO_ID_IDIOMA] ON CI.[KZN_DESPERDICIO] ([ID_IDIOMA] ASC) INCLUDE ([NM_DESPERDICIO]) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_KAIZEN_HIERARQUIA]') AND name = N'IX_KZN_KAIZEN_HIERARQUIA_KAIZEN')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_KAIZEN_HIERARQUIA_KAIZEN] ON CI.[KZN_KAIZEN_HIERARQUIA] ([ID_USUARIO_LIDER] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA]') AND name = N'IX_KZN_LOG_PVC_KAIZEN')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_LOG_PVC_KAIZEN] ON CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA] ([ID_KAIZEN] ASC, [DT_OPERACAO] DESC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA_DETALHE]') AND name = N'IX_KZN_LOG_PVC_DETALHE_LOG')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_LOG_PVC_DETALHE_LOG] ON CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA_DETALHE] ([ID_LOG] ASC, [NM_CAMPO] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_MDM_HIERARQUIA]') AND name = N'IX_KZN_MDM_HIERARQUIA_EMAIL')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_MDM_HIERARQUIA_EMAIL] ON CI.[KZN_MDM_HIERARQUIA] ([CD_EMAIL] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_PEDRAVISAOCONSOLIDADA]') AND name = N'IX_KZN_PVC_CATEGORIA')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_PVC_CATEGORIA] ON CI.[KZN_PEDRAVISAOCONSOLIDADA] ([ID_CATEGORIA] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_PEDRAVISAOCONSOLIDADA]') AND name = N'IX_KZN_PVC_STATUS')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_PVC_STATUS] ON CI.[KZN_PEDRAVISAOCONSOLIDADA] ([ID_STATUS] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_PEDRAVISAOCONSOLIDADA]') AND name = N'IX_KZN_PVC_TIPO_KAIZEN')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_PVC_TIPO_KAIZEN] ON CI.[KZN_PEDRAVISAOCONSOLIDADA] ([ID_TIPO_KAIZEN] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_PEDRAVISAOCONSOLIDADA]') AND name = N'IX_KZN_PVC_USUARIO_LIDER')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_PVC_USUARIO_LIDER] ON CI.[KZN_PEDRAVISAOCONSOLIDADA] ([ID_USUARIO_LIDER] ASC) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_REPLICACAO]') AND name = N'IX_KZN_REPLICACAO_ID_IDIOMA')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_REPLICACAO_ID_IDIOMA] ON CI.[KZN_REPLICACAO] ([ID_IDIOMA] ASC) INCLUDE ([NM_REPLICACAO]) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_RESULTADOS]') AND name = N'IX_KZN_RESULTADOS_ID_IDIOMA')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_RESULTADOS_ID_IDIOMA] ON CI.[KZN_RESULTADOS] ([ID_IDIOMA] ASC) INCLUDE ([NM_RESULTADO]) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_STATUS]') AND name = N'IX_KZN_STATUS_ID_IDIOMA')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_STATUS_ID_IDIOMA] ON CI.[KZN_STATUS] ([ID_IDIOMA] ASC) INCLUDE ([NM_STATUS]) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'CI.[KZN_TIPO_KAIZEN]') AND name = N'IX_KZN_TIPO_KAIZEN_ID_IDIOMA')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KZN_TIPO_KAIZEN_ID_IDIOMA] ON CI.[KZN_TIPO_KAIZEN] ([ID_IDIOMA] ASC) INCLUDE ([NM_TIPO_KAIZEN]) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = NONE);
END
GO
/* ── CHECKs e chaves estrangeiras ── */
IF OBJECT_ID(N'CI.[CK_KZN_LOG_PVC_TIPO]', N'C') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA] WITH CHECK ADD CONSTRAINT [CK_KZN_LOG_PVC_TIPO] CHECK ([TP_OPERACAO]='A' OR [TP_OPERACAO]='C');
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_ADMIN_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_ADMIN] WITH CHECK ADD CONSTRAINT [FK_KZN_ADMIN_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_APROVADOR_MDM_MATRICULA]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_APROVADOR] WITH CHECK ADD CONSTRAINT [FK_KZN_APROVADOR_MDM_MATRICULA] FOREIGN KEY ([CD_MATRICULA]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([CD_MATRICULA]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_APROVADOR_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_APROVADOR] WITH CHECK ADD CONSTRAINT [FK_KZN_APROVADOR_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_CATEGORIA_IDIOMA]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_CATEGORIA] WITH CHECK ADD CONSTRAINT [FK_KZN_CATEGORIA_IDIOMA] FOREIGN KEY ([ID_IDIOMA]) REFERENCES [CI].[KZN_IDIOMA] ([ID_IDIOMA]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_CATEGORIA_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_CATEGORIA] WITH CHECK ADD CONSTRAINT [FK_KZN_CATEGORIA_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_DESPERDICIO_IDIOMA]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_DESPERDICIO] WITH CHECK ADD CONSTRAINT [FK_KZN_DESPERDICIO_IDIOMA] FOREIGN KEY ([ID_IDIOMA]) REFERENCES [CI].[KZN_IDIOMA] ([ID_IDIOMA]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_DESPERDICIO_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_DESPERDICIO] WITH CHECK ADD CONSTRAINT [FK_KZN_DESPERDICIO_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_HIST_PVC_APROVADOR]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_HIST_PEDRAVISAOCONSOLIDADA] WITH CHECK ADD CONSTRAINT [FK_KZN_HIST_PVC_APROVADOR] FOREIGN KEY ([ID_APROVADOR]) REFERENCES [CI].[KZN_HIST_APROVADOR] ([ID_APROVADOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_IDIOMA_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_IDIOMA] WITH CHECK ADD CONSTRAINT [FK_KZN_IDIOMA_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_KZDESP_KAIZEN]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_KAIZEN_DESPERDICIO] WITH CHECK ADD CONSTRAINT [FK_KZN_KZDESP_KAIZEN] FOREIGN KEY ([ID_KAIZEN]) REFERENCES [CI].[KZN_PEDRAVISAOCONSOLIDADA] ([ID_KAIZEN]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_KAIZEN_HIERARQUIA_KAIZEN]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_KAIZEN_HIERARQUIA] WITH CHECK ADD CONSTRAINT [FK_KZN_KAIZEN_HIERARQUIA_KAIZEN] FOREIGN KEY ([ID_KAIZEN]) REFERENCES [CI].[KZN_PEDRAVISAOCONSOLIDADA] ([ID_KAIZEN]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_KAIZEN_HIERARQUIA_LIDER]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_KAIZEN_HIERARQUIA] WITH CHECK ADD CONSTRAINT [FK_KZN_KAIZEN_HIERARQUIA_LIDER] FOREIGN KEY ([ID_KAIZEN], [ID_USUARIO_LIDER]) REFERENCES [CI].[KZN_PEDRAVISAOCONSOLIDADA] ([ID_KAIZEN], [ID_USUARIO_LIDER]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_KAIZEN_HIERARQUIA_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_KAIZEN_HIERARQUIA] WITH CHECK ADD CONSTRAINT [FK_KZN_KAIZEN_HIERARQUIA_USUARIO] FOREIGN KEY ([ID_USUARIO_LIDER]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_LOG_PVC_KAIZEN]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA] WITH CHECK ADD CONSTRAINT [FK_KZN_LOG_PVC_KAIZEN] FOREIGN KEY ([ID_KAIZEN]) REFERENCES [CI].[KZN_PEDRAVISAOCONSOLIDADA] ([ID_KAIZEN]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_LOG_PVC_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA] WITH CHECK ADD CONSTRAINT [FK_KZN_LOG_PVC_USUARIO] FOREIGN KEY ([ID_USUARIO_OPERACAO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_LOG_PVC_DETALHE_LOG]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_LOG_PEDRAVISAOCONSOLIDADA_DETALHE] WITH CHECK ADD CONSTRAINT [FK_KZN_LOG_PVC_DETALHE_LOG] FOREIGN KEY ([ID_LOG]) REFERENCES [CI].[KZN_LOG_PEDRAVISAOCONSOLIDADA] ([ID_LOG]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_MDM_TIPO_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_MDM_HIERARQUIA] WITH CHECK ADD CONSTRAINT [FK_KZN_MDM_TIPO_USUARIO] FOREIGN KEY ([ID_TIPO_USUARIO]) REFERENCES [CI].[KZN_TIPO_USUARIO] ([ID_TIPO_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_MOEDA_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_MOEDA] WITH CHECK ADD CONSTRAINT [FK_KZN_MOEDA_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_PVC_APROVADOR]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_PEDRAVISAOCONSOLIDADA] WITH CHECK ADD CONSTRAINT [FK_KZN_PVC_APROVADOR] FOREIGN KEY ([ID_APROVADOR]) REFERENCES [CI].[KZN_APROVADOR] ([ID_APROVADOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_PVC_MOEDA]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_PEDRAVISAOCONSOLIDADA] WITH CHECK ADD CONSTRAINT [FK_KZN_PVC_MOEDA] FOREIGN KEY ([ID_MOEDA]) REFERENCES [CI].[KZN_MOEDA] ([ID_MOEDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_PVC_USUARIO_ATUALIZACAO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_PEDRAVISAOCONSOLIDADA] WITH CHECK ADD CONSTRAINT [FK_KZN_PVC_USUARIO_ATUALIZACAO] FOREIGN KEY ([ID_USUARIO_ATUALIZACAO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_PVC_USUARIO_CADASTRO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_PEDRAVISAOCONSOLIDADA] WITH CHECK ADD CONSTRAINT [FK_KZN_PVC_USUARIO_CADASTRO] FOREIGN KEY ([ID_USUARIO_CADASTRO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_PVC_USUARIO_LIDER]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_PEDRAVISAOCONSOLIDADA] WITH CHECK ADD CONSTRAINT [FK_KZN_PVC_USUARIO_LIDER] FOREIGN KEY ([ID_USUARIO_LIDER]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_REPLICACAO_IDIOMA]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_REPLICACAO] WITH CHECK ADD CONSTRAINT [FK_KZN_REPLICACAO_IDIOMA] FOREIGN KEY ([ID_IDIOMA]) REFERENCES [CI].[KZN_IDIOMA] ([ID_IDIOMA]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_REPLICACAO_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_REPLICACAO] WITH CHECK ADD CONSTRAINT [FK_KZN_REPLICACAO_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_RESULTADO_KAIZEN_KAIZEN]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_RESULTADO_KAIZEN] WITH CHECK ADD CONSTRAINT [FK_KZN_RESULTADO_KAIZEN_KAIZEN] FOREIGN KEY ([ID_KAIZEN]) REFERENCES [CI].[KZN_PEDRAVISAOCONSOLIDADA] ([ID_KAIZEN]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_RESULTADOS_IDIOMA]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_RESULTADOS] WITH CHECK ADD CONSTRAINT [FK_KZN_RESULTADOS_IDIOMA] FOREIGN KEY ([ID_IDIOMA]) REFERENCES [CI].[KZN_IDIOMA] ([ID_IDIOMA]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_RESULTADOS_TIPO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_RESULTADOS] WITH CHECK ADD CONSTRAINT [FK_KZN_RESULTADOS_TIPO] FOREIGN KEY ([ID_TIPO_RESULTADO], [ID_IDIOMA]) REFERENCES [CI].[KZN_TIPO_RESULTADO] ([ID_TIPO_RESULTADO], [ID_IDIOMA]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_RESULTADOS_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_RESULTADOS] WITH CHECK ADD CONSTRAINT [FK_KZN_RESULTADOS_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_STATUS_IDIOMA]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_STATUS] WITH CHECK ADD CONSTRAINT [FK_KZN_STATUS_IDIOMA] FOREIGN KEY ([ID_IDIOMA]) REFERENCES [CI].[KZN_IDIOMA] ([ID_IDIOMA]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_TIPO_KAIZEN_IDIOMA]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_TIPO_KAIZEN] WITH CHECK ADD CONSTRAINT [FK_KZN_TIPO_KAIZEN_IDIOMA] FOREIGN KEY ([ID_IDIOMA]) REFERENCES [CI].[KZN_IDIOMA] ([ID_IDIOMA]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_TIPO_KAIZEN_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_TIPO_KAIZEN] WITH CHECK ADD CONSTRAINT [FK_KZN_TIPO_KAIZEN_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_TIPO_RESULTADO_IDIOMA]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_TIPO_RESULTADO] WITH CHECK ADD CONSTRAINT [FK_KZN_TIPO_RESULTADO_IDIOMA] FOREIGN KEY ([ID_IDIOMA]) REFERENCES [CI].[KZN_IDIOMA] ([ID_IDIOMA]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_TIPO_RESULTADO_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_TIPO_RESULTADO] WITH CHECK ADD CONSTRAINT [FK_KZN_TIPO_RESULTADO_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
IF OBJECT_ID(N'CI.[FK_KZN_TIPO_USUARIO_USUARIO]', N'F') IS NULL
BEGIN
    ALTER TABLE CI.[KZN_TIPO_USUARIO] WITH CHECK ADD CONSTRAINT [FK_KZN_TIPO_USUARIO_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [CI].[KZN_MDM_HIERARQUIA] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;
END
GO
/* ── Triggers ── */
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_ADMIN_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_ADMIN_UPD ON CI.KZN_ADMIN AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_ADMIN T JOIN inserted i ON i.ID_ADMIN = T.ID_ADMIN;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_ANALISE_DUP_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_ANALISE_DUP_UPD ON CI.KZN_ANALISE_DUPLICIDADE AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    -- Sem PK, o carimbo casa pelo ID_KAIZEN das linhas afetadas.
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_ANALISE_DUPLICIDADE T JOIN inserted i ON i.ID_KAIZEN = T.ID_KAIZEN;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_APROVADOR_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_APROVADOR_UPD ON CI.KZN_APROVADOR AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_APROVADOR T JOIN inserted i ON i.ID_APROVADOR = T.ID_APROVADOR;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_CATEGORIA_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_CATEGORIA_UPD ON CI.KZN_CATEGORIA AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_CATEGORIA T JOIN inserted i ON i.ID_CATEGORIA = T.ID_CATEGORIA AND i.ID_IDIOMA = T.ID_IDIOMA;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_DESPERDICIO_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_DESPERDICIO_UPD ON CI.KZN_DESPERDICIO AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_DESPERDICIO T JOIN inserted i ON i.ID_DESPERDICIO = T.ID_DESPERDICIO AND i.ID_IDIOMA = T.ID_IDIOMA;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_IDIOMA_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_IDIOMA_UPD ON CI.KZN_IDIOMA AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_IDIOMA T JOIN inserted i ON i.ID_IDIOMA = T.ID_IDIOMA;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_KZDESP_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_KZDESP_UPD ON CI.KZN_KAIZEN_DESPERDICIO AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_KAIZEN_DESPERDICIO T
        JOIN inserted i ON i.ID_KAIZEN = T.ID_KAIZEN AND i.ID_DESPERDICIO = T.ID_DESPERDICIO;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_MDM_HIERARQUIA_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
/* ==============================================================================
   18. TRIGGERS — atualização automática de DT_ATUALIZACAO no UPDATE
   (tabelas mestre / auxiliares com PK simples ou composta)
   ============================================================================== */
CREATE   TRIGGER CI.TR_KZN_MDM_HIERARQUIA_UPD ON CI.KZN_MDM_HIERARQUIA AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_MDM_HIERARQUIA T JOIN inserted i ON i.ID_USUARIO = T.ID_USUARIO;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_MEMBROS_EQUIPE_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_MEMBROS_EQUIPE_UPD ON CI.KZN_MEMBROS_EQUIPE AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_MEMBROS_EQUIPE T
        JOIN inserted i ON i.ID_KAIZEN = T.ID_KAIZEN AND i.ID_USUARIO = T.ID_USUARIO;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_MOEDA_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_MOEDA_UPD ON CI.KZN_MOEDA AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_MOEDA T JOIN inserted i ON i.ID_MOEDA = T.ID_MOEDA;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_PVC_INS]', N'TR') IS NULL
BEGIN
    EXEC (N'
/* ==============================================================================
   19. TRIGGERS ESPECIAIS — CI.KZN_PEDRAVISAOCONSOLIDADA
   (gravação no log de auditoria, com diff
   campo a campo em CI.KZN_LOG_PEDRAVISAOCONSOLIDADA_DETALHE nas
   atualizações — ver seção 14b)
   ============================================================================== */
CREATE   TRIGGER CI.TR_KZN_PVC_INS ON CI.KZN_PEDRAVISAOCONSOLIDADA AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO CI.KZN_LOG_PEDRAVISAOCONSOLIDADA (ID_LOG, ID_KAIZEN, TP_OPERACAO, DT_OPERACAO, ID_USUARIO_OPERACAO)
    SELECT NEXT VALUE FOR CI.SEQ_KZN_LOG_PVC, ID_KAIZEN, ''C'', SYSDATETIME(), ID_USUARIO_CADASTRO
    FROM inserted;
    -- Sem linha de detalhe aqui: criação não tem "valor anterior" a comparar.
    -- Esta linha ''C'' é o ÚNICO registro da data de criação do Kaizen desde
    -- que a coluna DT_CRIACAO foi removida da tabela principal.
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_PVC_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_PVC_UPD ON CI.KZN_PEDRAVISAOCONSOLIDADA AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;

    -- DT_CRIACAO NÃO é carimbada aqui: é data de criação, gravada no INSERT.
    -- Sobrescrevê-la a cada UPDATE destruiria o dado original.

    -- Uma linha de cabeçalho de log por Kaizen afetado, capturando o
    -- ID_LOG recém-gerado (OUTPUT) pra ligar as linhas de detalhe geradas
    -- logo abaixo — necessário porque um único UPDATE pode afetar mais de
    -- um Kaizen de uma vez, cada um com seu próprio ID_LOG.
    DECLARE @logMap TABLE (ID_KAIZEN INT NOT NULL PRIMARY KEY, ID_LOG INT NOT NULL);

    -- DT_OPERACAO = SYSDATETIME(): o instante real da alteração. Antes
    -- vinha da coluna DT_ATUALIZACAO, que deixou de existir na tabela.
    INSERT INTO CI.KZN_LOG_PEDRAVISAOCONSOLIDADA (ID_LOG, ID_KAIZEN, TP_OPERACAO, DT_OPERACAO, ID_USUARIO_OPERACAO)
    OUTPUT inserted.ID_KAIZEN, inserted.ID_LOG INTO @logMap (ID_KAIZEN, ID_LOG)
    SELECT NEXT VALUE FOR CI.SEQ_KZN_LOG_PVC, i.ID_KAIZEN, ''A'', SYSDATETIME(), i.ID_USUARIO_ATUALIZACAO
    FROM inserted i;

    -- Diff campo a campo (seção 14b) — 1 linha por coluna de negócio cujo
    -- valor mudou nesta atualização. Comparação NULL-segura: "NOT (d.COL =
    -- i.COL OR (d.COL IS NULL AND i.COL IS NULL))" trata NULL=NULL como
    -- "não mudou" e qualquer outra combinação (incluindo um lado NULL) como
    -- mudança. DT_CRIACAO e ID_USUARIO_ATUALIZACAO ficam de fora: a
    -- primeira não muda, o segundo é metadado do cabeçalho gravado acima.
    INSERT INTO CI.KZN_LOG_PEDRAVISAOCONSOLIDADA_DETALHE (ID_LOG_DETALHE, ID_LOG, NM_CAMPO, VL_ANTERIOR, VL_NOVO)
    SELECT NEXT VALUE FOR CI.SEQ_KZN_LOG_PVC_DETALHE, x.ID_LOG, x.NM_CAMPO, x.VL_ANTERIOR, x.VL_NOVO
    FROM (
        SELECT lm.ID_LOG, ''ID_USUARIO_CADASTRO'' AS NM_CAMPO, CONVERT(VARCHAR(300), d.ID_USUARIO_CADASTRO) AS VL_ANTERIOR, CONVERT(VARCHAR(300), i.ID_USUARIO_CADASTRO) AS VL_NOVO
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.ID_USUARIO_CADASTRO = i.ID_USUARIO_CADASTRO OR (d.ID_USUARIO_CADASTRO IS NULL AND i.ID_USUARIO_CADASTRO IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''ID_USUARIO_LIDER'', CONVERT(VARCHAR(300), d.ID_USUARIO_LIDER), CONVERT(VARCHAR(300), i.ID_USUARIO_LIDER)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.ID_USUARIO_LIDER = i.ID_USUARIO_LIDER OR (d.ID_USUARIO_LIDER IS NULL AND i.ID_USUARIO_LIDER IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''NM_KAIZEN'', CONVERT(VARCHAR(300), d.NM_KAIZEN), CONVERT(VARCHAR(300), i.NM_KAIZEN)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.NM_KAIZEN = i.NM_KAIZEN OR (d.NM_KAIZEN IS NULL AND i.NM_KAIZEN IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''ID_CATEGORIA'', CONVERT(VARCHAR(300), d.ID_CATEGORIA), CONVERT(VARCHAR(300), i.ID_CATEGORIA)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.ID_CATEGORIA = i.ID_CATEGORIA OR (d.ID_CATEGORIA IS NULL AND i.ID_CATEGORIA IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''ID_REPLICACAO'', CONVERT(VARCHAR(300), d.ID_REPLICACAO), CONVERT(VARCHAR(300), i.ID_REPLICACAO)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.ID_REPLICACAO = i.ID_REPLICACAO OR (d.ID_REPLICACAO IS NULL AND i.ID_REPLICACAO IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''DS_PROBLEMA'', CONVERT(VARCHAR(300), d.DS_PROBLEMA), CONVERT(VARCHAR(300), i.DS_PROBLEMA)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.DS_PROBLEMA = i.DS_PROBLEMA OR (d.DS_PROBLEMA IS NULL AND i.DS_PROBLEMA IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''DS_OBJETIVO'', CONVERT(VARCHAR(300), d.DS_OBJETIVO), CONVERT(VARCHAR(300), i.DS_OBJETIVO)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.DS_OBJETIVO = i.DS_OBJETIVO OR (d.DS_OBJETIVO IS NULL AND i.DS_OBJETIVO IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''ID_STATUS'', CONVERT(VARCHAR(300), d.ID_STATUS), CONVERT(VARCHAR(300), i.ID_STATUS)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.ID_STATUS = i.ID_STATUS OR (d.ID_STATUS IS NULL AND i.ID_STATUS IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''ID_APROVADOR'', CONVERT(VARCHAR(300), d.ID_APROVADOR), CONVERT(VARCHAR(300), i.ID_APROVADOR)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.ID_APROVADOR = i.ID_APROVADOR OR (d.ID_APROVADOR IS NULL AND i.ID_APROVADOR IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''URL_IMG_ANTES'', CONVERT(VARCHAR(300), d.URL_IMG_ANTES), CONVERT(VARCHAR(300), i.URL_IMG_ANTES)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.URL_IMG_ANTES = i.URL_IMG_ANTES OR (d.URL_IMG_ANTES IS NULL AND i.URL_IMG_ANTES IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''DS_ESTADO_ANTES'', CONVERT(VARCHAR(300), d.DS_ESTADO_ANTES), CONVERT(VARCHAR(300), i.DS_ESTADO_ANTES)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.DS_ESTADO_ANTES = i.DS_ESTADO_ANTES OR (d.DS_ESTADO_ANTES IS NULL AND i.DS_ESTADO_ANTES IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''URL_IMG_DEPOIS'', CONVERT(VARCHAR(300), d.URL_IMG_DEPOIS), CONVERT(VARCHAR(300), i.URL_IMG_DEPOIS)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.URL_IMG_DEPOIS = i.URL_IMG_DEPOIS OR (d.URL_IMG_DEPOIS IS NULL AND i.URL_IMG_DEPOIS IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''DS_ESTADO_DEPOIS'', CONVERT(VARCHAR(300), d.DS_ESTADO_DEPOIS), CONVERT(VARCHAR(300), i.DS_ESTADO_DEPOIS)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.DS_ESTADO_DEPOIS = i.DS_ESTADO_DEPOIS OR (d.DS_ESTADO_DEPOIS IS NULL AND i.DS_ESTADO_DEPOIS IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''URL_REFERENCIA'', CONVERT(VARCHAR(300), d.URL_REFERENCIA), CONVERT(VARCHAR(300), i.URL_REFERENCIA)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.URL_REFERENCIA = i.URL_REFERENCIA OR (d.URL_REFERENCIA IS NULL AND i.URL_REFERENCIA IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''DS_COMPARA_META'', CONVERT(VARCHAR(300), d.DS_COMPARA_META), CONVERT(VARCHAR(300), i.DS_COMPARA_META)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.DS_COMPARA_META = i.DS_COMPARA_META OR (d.DS_COMPARA_META IS NULL AND i.DS_COMPARA_META IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''DS_LICOES_APRENDIDAS'', CONVERT(VARCHAR(300), d.DS_LICOES_APRENDIDAS), CONVERT(VARCHAR(300), i.DS_LICOES_APRENDIDAS)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.DS_LICOES_APRENDIDAS = i.DS_LICOES_APRENDIDAS OR (d.DS_LICOES_APRENDIDAS IS NULL AND i.DS_LICOES_APRENDIDAS IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''VL_RESULTADO_FINANCEIRO'', CONVERT(VARCHAR(300), d.VL_RESULTADO_FINANCEIRO), CONVERT(VARCHAR(300), i.VL_RESULTADO_FINANCEIRO)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.VL_RESULTADO_FINANCEIRO = i.VL_RESULTADO_FINANCEIRO OR (d.VL_RESULTADO_FINANCEIRO IS NULL AND i.VL_RESULTADO_FINANCEIRO IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''ID_MOEDA'', CONVERT(VARCHAR(300), d.ID_MOEDA), CONVERT(VARCHAR(300), i.ID_MOEDA)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.ID_MOEDA = i.ID_MOEDA OR (d.ID_MOEDA IS NULL AND i.ID_MOEDA IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''DS_RESULTADO_ALCANCADO'', CONVERT(VARCHAR(300), d.DS_RESULTADO_ALCANCADO), CONVERT(VARCHAR(300), i.DS_RESULTADO_ALCANCADO)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.DS_RESULTADO_ALCANCADO = i.DS_RESULTADO_ALCANCADO OR (d.DS_RESULTADO_ALCANCADO IS NULL AND i.DS_RESULTADO_ALCANCADO IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''DT_CONCLUSAO'', CONVERT(VARCHAR(300), d.DT_CONCLUSAO, 23), CONVERT(VARCHAR(300), i.DT_CONCLUSAO, 23)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.DT_CONCLUSAO = i.DT_CONCLUSAO OR (d.DT_CONCLUSAO IS NULL AND i.DT_CONCLUSAO IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''DS_MOTIVO'', CONVERT(VARCHAR(300), d.DS_MOTIVO), CONVERT(VARCHAR(300), i.DS_MOTIVO)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.DS_MOTIVO = i.DS_MOTIVO OR (d.DS_MOTIVO IS NULL AND i.DS_MOTIVO IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''SG_GM'', CONVERT(VARCHAR(300), d.SG_GM), CONVERT(VARCHAR(300), i.SG_GM)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.SG_GM = i.SG_GM OR (d.SG_GM IS NULL AND i.SG_GM IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''URL_GM'', CONVERT(VARCHAR(300), d.URL_GM), CONVERT(VARCHAR(300), i.URL_GM)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.URL_GM = i.URL_GM OR (d.URL_GM IS NULL AND i.URL_GM IS NULL))
        UNION ALL
        SELECT lm.ID_LOG, ''ID_TIPO_KAIZEN'', CONVERT(VARCHAR(300), d.ID_TIPO_KAIZEN), CONVERT(VARCHAR(300), i.ID_TIPO_KAIZEN)
        FROM inserted i JOIN deleted d ON d.ID_KAIZEN = i.ID_KAIZEN JOIN @logMap lm ON lm.ID_KAIZEN = i.ID_KAIZEN
        WHERE NOT (d.ID_TIPO_KAIZEN = i.ID_TIPO_KAIZEN OR (d.ID_TIPO_KAIZEN IS NULL AND i.ID_TIPO_KAIZEN IS NULL))
    ) x;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_REPLICACAO_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_REPLICACAO_UPD ON CI.KZN_REPLICACAO AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_REPLICACAO T JOIN inserted i ON i.ID_REPLICACAO = T.ID_REPLICACAO AND i.ID_IDIOMA = T.ID_IDIOMA;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_RESULTADO_KAIZEN_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_RESULTADO_KAIZEN_UPD ON CI.KZN_RESULTADO_KAIZEN AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_RESULTADO_KAIZEN T
        JOIN inserted i ON i.ID_KAIZEN = T.ID_KAIZEN AND i.ID_RESULTADO = T.ID_RESULTADO;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_RESULTADOS_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_RESULTADOS_UPD ON CI.KZN_RESULTADOS AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_RESULTADOS T JOIN inserted i ON i.ID_RESULTADO = T.ID_RESULTADO AND i.ID_IDIOMA = T.ID_IDIOMA;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_STATUS_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_STATUS_UPD ON CI.KZN_STATUS AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_STATUS T JOIN inserted i ON i.ID_STATUS = T.ID_STATUS AND i.ID_IDIOMA = T.ID_IDIOMA;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_TIPO_KAIZEN_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_TIPO_KAIZEN_UPD ON CI.KZN_TIPO_KAIZEN AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_TIPO_KAIZEN T JOIN inserted i
          ON i.ID_TIPO_KAIZEN = T.ID_TIPO_KAIZEN AND i.ID_IDIOMA = T.ID_IDIOMA;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_TIPO_RESULTADO_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_TIPO_RESULTADO_UPD ON CI.KZN_TIPO_RESULTADO AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_TIPO_RESULTADO T JOIN inserted i ON i.ID_TIPO_RESULTADO = T.ID_TIPO_RESULTADO AND i.ID_IDIOMA = T.ID_IDIOMA;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'CI.[TR_KZN_TIPO_USUARIO_UPD]', N'TR') IS NULL
BEGIN
    EXEC (N'
CREATE   TRIGGER CI.TR_KZN_TIPO_USUARIO_UPD ON CI.KZN_TIPO_USUARIO AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DT_ATUALIZACAO)
        UPDATE T SET DT_ATUALIZACAO = SYSDATETIME()
        FROM CI.KZN_TIPO_USUARIO T JOIN inserted i ON i.ID_TIPO_USUARIO = T.ID_TIPO_USUARIO;
END
');
END
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
/* ── Propriedades estendidas ── */
IF NOT EXISTS (SELECT 1 FROM sys.fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'CI', N'TABLE', N'KZN_TIPO_USUARIO', NULL, NULL))
    EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Cadastro de tipos/perfis de usuário do Kaizen.', @level0type = N'SCHEMA', @level0name = N'CI', @level1type = N'TABLE', @level1name = N'KZN_TIPO_USUARIO';
GO
IF NOT EXISTS (SELECT 1 FROM sys.fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'CI', N'TABLE', N'KZN_TIPO_USUARIO', N'COLUMN', N'DT_ATUALIZACAO'))
    EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Data da última atualização do registro.', @level0type = N'SCHEMA', @level0name = N'CI', @level1type = N'TABLE', @level1name = N'KZN_TIPO_USUARIO', @level2type = N'COLUMN', @level2name = N'DT_ATUALIZACAO';
GO
IF NOT EXISTS (SELECT 1 FROM sys.fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'CI', N'TABLE', N'KZN_TIPO_USUARIO', N'COLUMN', N'ID_TIPO_USUARIO'))
    EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Identificador do tipo de usuário (PK).', @level0type = N'SCHEMA', @level0name = N'CI', @level1type = N'TABLE', @level1name = N'KZN_TIPO_USUARIO', @level2type = N'COLUMN', @level2name = N'ID_TIPO_USUARIO';
GO
IF NOT EXISTS (SELECT 1 FROM sys.fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'CI', N'TABLE', N'KZN_TIPO_USUARIO', N'COLUMN', N'ID_USUARIO'))
    EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Usuário (MDM) responsável/administrador do cadastro.', @level0type = N'SCHEMA', @level0name = N'CI', @level1type = N'TABLE', @level1name = N'KZN_TIPO_USUARIO', @level2type = N'COLUMN', @level2name = N'ID_USUARIO';
GO
IF NOT EXISTS (SELECT 1 FROM sys.fn_listextendedproperty(N'MS_Description', N'SCHEMA', N'CI', N'TABLE', N'KZN_TIPO_USUARIO', N'COLUMN', N'NM_USUARIO'))
    EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Nome do tipo de usuário.', @level0type = N'SCHEMA', @level0name = N'CI', @level1type = N'TABLE', @level1name = N'KZN_TIPO_USUARIO', @level2type = N'COLUMN', @level2name = N'NM_USUARIO';
GO
/* ── Conferência: esperado x criado ── */
SELECT OBJETO = e.OBJETO, ESPERADO = e.QTD, CRIADO = c.QTD, RESULTADO = CASE WHEN e.QTD = c.QTD THEN 'OK' ELSE 'DIVERGE' END
FROM (VALUES
    (N'Tabelas', 29),
    (N'Colunas', 242),
    (N'PK e UNIQUE', 38),
    (N'Defaults', 35),
    (N'Colunas identity', 0),
    (N'Índices', 15),
    (N'CHECKs', 1),
    (N'Chaves estrangeiras', 35),
    (N'FKs confiáveis', 35),
    (N'Views, funções e procedures', 0),
    (N'Triggers', 19),
    (N'Sequences', 2),
    (N'Sinônimos', 0),
    (N'Propriedades estendidas', 5)
) e (OBJETO, QTD)
JOIN (
    SELECT N'Tabelas', COUNT(*) FROM sys.tables WHERE schema_id = SCHEMA_ID(N'CI')
    UNION ALL SELECT N'Colunas', COUNT(*) FROM sys.columns c JOIN sys.tables t ON t.object_id = c.object_id WHERE t.schema_id = SCHEMA_ID(N'CI')
    UNION ALL SELECT N'PK e UNIQUE', COUNT(*) FROM sys.key_constraints k JOIN sys.tables t ON t.object_id = k.parent_object_id WHERE t.schema_id = SCHEMA_ID(N'CI')
    UNION ALL SELECT N'Defaults', COUNT(*) FROM sys.default_constraints d JOIN sys.tables t ON t.object_id = d.parent_object_id WHERE t.schema_id = SCHEMA_ID(N'CI')
    UNION ALL SELECT N'Colunas identity', COUNT(*) FROM sys.identity_columns i JOIN sys.tables t ON t.object_id = i.object_id WHERE t.schema_id = SCHEMA_ID(N'CI')
    UNION ALL SELECT N'Índices', COUNT(*) FROM sys.indexes i JOIN sys.objects o ON o.object_id = i.object_id WHERE o.schema_id = SCHEMA_ID(N'CI') AND o.type IN ('U','V') AND i.type IN (1,2) AND i.is_primary_key = 0 AND i.is_unique_constraint = 0 AND i.is_hypothetical = 0
    UNION ALL SELECT N'CHECKs', COUNT(*) FROM sys.check_constraints c JOIN sys.tables t ON t.object_id = c.parent_object_id WHERE t.schema_id = SCHEMA_ID(N'CI')
    UNION ALL SELECT N'Chaves estrangeiras', COUNT(*) FROM sys.foreign_keys f JOIN sys.tables t ON t.object_id = f.parent_object_id WHERE t.schema_id = SCHEMA_ID(N'CI')
    UNION ALL SELECT N'FKs confiáveis', COUNT(*) FROM sys.foreign_keys f JOIN sys.tables t ON t.object_id = f.parent_object_id WHERE t.schema_id = SCHEMA_ID(N'CI') AND f.is_not_trusted = 0
    UNION ALL SELECT N'Views, funções e procedures', COUNT(*) FROM sys.objects WHERE schema_id = SCHEMA_ID(N'CI') AND type IN ('V','P','FN','IF','TF')
    UNION ALL SELECT N'Triggers', COUNT(*) FROM sys.objects WHERE schema_id = SCHEMA_ID(N'CI') AND type = 'TR'
    UNION ALL SELECT N'Sequences', COUNT(*) FROM sys.sequences WHERE schema_id = SCHEMA_ID(N'CI')
    UNION ALL SELECT N'Sinônimos', COUNT(*) FROM sys.synonyms WHERE schema_id = SCHEMA_ID(N'CI')
    UNION ALL SELECT N'Propriedades estendidas', COUNT(*) FROM sys.extended_properties ep JOIN sys.objects o ON o.object_id = ep.major_id WHERE ep.class IN (1, 7) AND o.schema_id = SCHEMA_ID(N'CI')
) c (OBJETO, QTD) ON c.OBJETO = e.OBJETO;
GO
SET NOEXEC OFF;
GO